# Generated by Django 4.2.9 on 2025-02-05 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("score", models.IntegerField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-score"],},
        ),
    ]
